[package]
name = "Examples"
version = "0.0.0"

[addresses]
move_gas_optimization = "0x2df009d3324a47700fc326a3f9c910549110fba73508a72d75cfbd85ef1e58f8"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "aptos-node-v1.2.0" }
